name: football_trivia
description: "A new Football Trivia mobile app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  animated_bottom_navigation_bar: ^1.4.0
  animated_leaderboard: ^0.1.4
  supabase_flutter: ^2.5.4
  just_audio: ^0.10.5
  speech_to_text: ^7.3.0
  shared_preferences: ^2.2.2
  glossy: ^0.0.5
  infinite_carousel: ^1.0.2
  xml: ^6.5.0
  permission_handler: ^12.0.1
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.4.7
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

# Native Splash Screen Configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/Logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
    - assets/images/background.jpg
    - assets/images/profile11.jpg
    - assets/images/Logo.png
    - assets/images/Layer 3.png
    - assets/images/GUESS THE PLAYER.png
    - assets/images/google_icon.png
    - assets/images/splash_bg.png
    - assets/images/Gemini_Generated_Image_p7lysbp7lysbp7ly.png
    - assets/images/QuestionsFrames/
    - assets/images/backgrounds/
    - assets/images/Leagues/
    - assets/images/maps/


